// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Models.EF;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20260621112804_s10")]
    partial class s10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Database.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Core.Database.Models.Authorized", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("Authorized");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b320f6af-edbc-4031-8977-a407e208cc41"),
                            GroupId = new Guid("d0cfdf00-afc9-4567-a9ec-0f0db44a18bd"),
                            RoleId = new Guid("b5f8852e-1a0f-4fee-a821-1c982c33f9aa")
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ea90800-ec76-4e3c-83f5-0d7446510385"),
                            CreatedBy = new Guid("fd48367d-f4a1-4e0b-a1f6-9d72afcebcc9"),
                            CreatedOn = new DateTime(2026, 6, 21, 18, 28, 1, 275, DateTimeKind.Local).AddTicks(2539),
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("d951dd74-a153-408c-ab60-44e51bb51f47"),
                            CreatedBy = new Guid("fd48367d-f4a1-4e0b-a1f6-9d72afcebcc9"),
                            CreatedOn = new DateTime(2026, 6, 21, 18, 28, 1, 275, DateTimeKind.Local).AddTicks(2542),
                            Name = "Authorized",
                            ParentId = new Guid("5ea90800-ec76-4e3c-83f5-0d7446510385")
                        },
                        new
                        {
                            Id = new Guid("74d373c3-dcf6-4634-8a46-7700b82dbe4d"),
                            CreatedBy = new Guid("fd48367d-f4a1-4e0b-a1f6-9d72afcebcc9"),
                            CreatedOn = new DateTime(2026, 6, 21, 18, 28, 1, 275, DateTimeKind.Local).AddTicks(2552),
                            Name = "Nhóm quyền",
                            ParentId = new Guid("d951dd74-a153-408c-ab60-44e51bb51f47")
                        },
                        new
                        {
                            Id = new Guid("86700b84-de54-426a-9748-da1bce88e424"),
                            CreatedBy = new Guid("fd48367d-f4a1-4e0b-a1f6-9d72afcebcc9"),
                            CreatedOn = new DateTime(2026, 6, 21, 18, 28, 1, 275, DateTimeKind.Local).AddTicks(2556),
                            Name = "Article",
                            ParentId = new Guid("5ea90800-ec76-4e3c-83f5-0d7446510385")
                        },
                        new
                        {
                            Id = new Guid("6b04bd80-c414-4836-ac8c-ca215b574f41"),
                            CreatedBy = new Guid("fd48367d-f4a1-4e0b-a1f6-9d72afcebcc9"),
                            CreatedOn = new DateTime(2026, 6, 21, 18, 28, 1, 275, DateTimeKind.Local).AddTicks(2560),
                            Name = "Product",
                            ParentId = new Guid("5ea90800-ec76-4e3c-83f5-0d7446510385")
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Core.Database.Models.Details", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("Core.Database.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0cfdf00-afc9-4567-a9ec-0f0db44a18bd"),
                            Name = "Quản trị viên"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd48367d-f4a1-4e0b-a1f6-9d72afcebcc9"),
                            CreatedOn = new DateTime(2026, 6, 21, 18, 28, 1, 275, DateTimeKind.Local).AddTicks(2414),
                            Email = "tranglu.24th@sv.dla.edu.vn",
                            GroupId = new Guid("d0cfdf00-afc9-4567-a9ec-0f0db44a18bd"),
                            LoginName = "tranglu",
                            Name = "Lâm Uyên Trang",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            Picture = "/img/users/uyentrang.jpg"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsComming")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5f8852e-1a0f-4fee-a821-1c982c33f9aa"),
                            CategoryId = new Guid("74d373c3-dcf6-4634-8a46-7700b82dbe4d"),
                            Code = "view-groups",
                            Name = "Xem danh sách"
                        },
                        new
                        {
                            Id = new Guid("1c229f8c-8d58-4de2-b7a5-96dde1bb9263"),
                            CategoryId = new Guid("74d373c3-dcf6-4634-8a46-7700b82dbe4d"),
                            Code = "edit-group",
                            Name = "Cập nhật"
                        },
                        new
                        {
                            Id = new Guid("a03ba290-d4a5-45cd-a255-be0a8ed3851d"),
                            CategoryId = new Guid("74d373c3-dcf6-4634-8a46-7700b82dbe4d"),
                            Code = "save-group",
                            Name = "Lưu"
                        },
                        new
                        {
                            Id = new Guid("70b8d810-029d-438f-9b41-f5ed8cbd7a31"),
                            CategoryId = new Guid("74d373c3-dcf6-4634-8a46-7700b82dbe4d"),
                            Code = "delete-group",
                            Name = "Xóa"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Authorized", b =>
                {
                    b.HasOne("Core.Database.Models.Group", "Group")
                        .WithMany("Authorizeds")
                        .HasForeignKey("GroupId");

                    b.HasOne("Core.Database.Models.Role", "Role")
                        .WithMany("Authorizeds")
                        .HasForeignKey("RoleId");

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Parent")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Core.Database.Models.Details", b =>
                {
                    b.HasOne("Core.Database.Models.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");

                    b.HasOne("Core.Database.Models.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Database.Models.Member", b =>
                {
                    b.HasOne("Core.Database.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Database.Models.Order", b =>
                {
                    b.HasOne("Core.Database.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Category")
                        .WithMany("Roles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Core.Database.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Core.Database.Models.Group", b =>
                {
                    b.Navigation("Authorizeds");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Core.Database.Models.Order", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.Navigation("Authorizeds");
                });
#pragma warning restore 612, 618
        }
    }
}
